# Generated by Django 4.0.4 on 2022-04-26 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='references')),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('D', 'Design'), ('VE', 'Video Edition')], default='D', max_length=2)),
                ('deadline', models.DateTimeField()),
                ('price', models.FloatField()),
                ('reserved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IP', 'In progress'), ('WA', 'Waiting for Approval'), ('F', 'Finished')], default='WA', max_length=2)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('references', models.ManyToManyField(to='jobs.references')),
            ],
        ),
    ]
